name: Terraform Apply

on:
  push:
    branches:
      - master

jobs:
  create-s3-bucket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.1.7'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Run Terraform
        run: echo "Lets do Terraform"
        
      - name: Initialize Terraform
        run: terraform init

      - name: Terraform plan
        run: terraform plan
      
      - name: Apply Terraform
        run: terraform apply -auto-approve